[package]
name = "cli-todo-list"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-watch = "8.5.3"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4"] }
